development:
  adapter: postgresql
  encoding: unicode
  database: tale_of_trumps_dev
  pool: 2

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || 2 %>
  connect_timeout: 10
